package se.student.liu.jessp088.vm.parsing;

/**
 * A token generated by the {@link Lexer} and used by the {@link Parser}.
 * A token is simply a wrapper around the type of the token (defined in {@link TokenType}) and the value of the token.
 * An example would be an "Identifier" token. An identifier is a name composed of letters and numbers.
 * So a generated token for that would be <code>Token("Identifier", "Hello")</code> where <code>Identifier</code> is the type
 * of the token and "Hello" is the value of the token.
 */
public class Token
{
	/** The type of the token */
	public final TokenType type;
	/** The value of the token */
	public final String value;

	public Token(final TokenType type, final String value) {
		this.type = type;
		this.value = value;
	}

	@Override
	public String toString() {
		return String.format("(%s %s)", type, value);
	}
}
